version: '3'

services:
  api:
    container_name: wongames_api
    image: gmcotta/wongames-api
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: sk_test_ChNLBXB1Nyrtb1rCquzrAvWP001EVjtePy
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: gmcotta/wongames-db
    ports:
      - '5432:5432'
