name: End to End
on: [pull_request]

jobs:
  end_to_end:
    runs_on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Build the stack
        run: docker-compose -f ./cypress/docker-compose.yml up -d
      -
        name: Waiting strapi server
        run: docker run --network container:wongames_api jwilder/dockerize -wait http://localhost:1337/admin -timeout 120s -wait-retry-interval 5s
      -
        name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      -
        uses: c-hive/gha-yarn-cache@v1
      -
        name: Install Dependencies
        run: yarn install
      -
        name: Build
        run: yarn build
      -
        name: Run Cypress
        run yarn test:e2e:ci

